### ISSUE TITLE
Unable to upload raw .fastq files

### ISSUE THREAD

**Issue by CD4655** [biomedbigdata/namco#33] opened 2022-07-13 10:08 UTC
After the .fastq files have been successfully uploaded and processed by DADA2, the program freezes (kicked from the server?), whether with or without a mapping file and regardless of whether the phylogenetic tree has been created. This occurs directly after the message of successful upload appears. Processing of raw .fastq files using LotuS2 was not tested. However, uploading of OTU/ASV tables is working fine.

**Comment by alex-d13** [comment] 2022-09-07 12:09
Hi @CD4655, sorry for the late response.

In case the issue is still appearing, could you send me 2 sample fastq files, which you tried to upload to alex.dietrich@tum.de?

Thank you,
Alex

**Comment by lonman99** [comment] 2022-11-24 13:28
Some taxa have NA in rownames in function utils.R/taxBinningNew, fixed by setting NAs to unkown: 
df[is.na(df)] <- "unknown"

**Comment by CD4655** [comment] 2022-12-14 13:25
Hi,


After the problem was solved for some time, the upload of raw .fastq files did not work again. Also, I realized that restoring an older session (May 2022) is not working. Attached is the respective R workspace.


Best,

Thomas Winogrodzki

________________________________
Von: lonman99 ***@***.***>
Gesendet: Donnerstag, 24. November 2022 14:28:13
An: biomedbigdata/namco
Cc: Winogrodzki, Thomas; Mention
Betreff: Re: [biomedbigdata/namco] Unable to upload raw .fastq files (Issue #33)


Some taxa have NA in rownames in function utils.R/taxBinningNew, fixed by setting NAs to unkown:
df[is.na(df)] <- "unknown"

**Comment by alex-d13** [comment] 2022-12-14 15:12
Hi Thomas,

Can you give a few more details what exactly is not working?
Did you also try it with the fastq files that did work the last time?

Regarding your session file, I cannot see it in here. Could you send it to us via email? 

Best,
Alex

**Comment by CD4655** [comment] 2022-12-14 17:12
Hi,

could you provide me with the mail adress I should send the files to?

Thank you!


Am 14.12.2022 16:12 schrieb Alexander Dietrich ***@***.***>:

Hi Thomas,

Can you give a few more details what exactly is not working?
Did you also try it with the fastq files that did work the last time?

Regarding your session file, I cannot see it in here. Could you send it to us via email?

Best,
Alex

**Comment by alex-d13** [comment] 2022-12-15 12:04
I think we already had email contact, but here is the email address: alex.dietrich@tum.de

**Closed** 2023-01-12 13:28 UTC
Labels: bug
